document.write("CFB Cursos<br><br>");
document.write("100");
document.write("<hr>");
document.write(100);
document.write("<hr>");
document.write("100"+100);
document.write("<hr>");
document.write(100+150);
document.write("<hr>");
document.write("Estudos importntes<br>JavaScript");
document.write("<hr>");
document.write("<p style='color:#f00'>Estudos importntes<br>JavaScript</p>");
document.write("<hr>");